# This isn't ideal because I'd rather it only run when the tftpd-hpa package
# is updated, but I don't have a way of determining that.

name: Autoupdate build on base-image change (debian:stable-slim)

on:
  schedule:
    # only run once a week.  Odds are pretty good that if there is a tftpd
    # update then it won't happen often.  The more likely scenario is that
    # we're rebuilding based on debian:stable-slim changes.
    - cron:  '42 21 * * 1'
  workflow_dispatch:
    inputs:
      force_build:
        description: 'Force build'
        required: true
        default: 'no'
        type: choice
        options:
          - "no"
          - "yes"

jobs:
  check:
    name: check for new release of debian:stable-slim
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image: debian:stable-slim
          image: rfdrake/tftpd-hpa:latest
          platforms: linux/amd64,linux/arm64

  build:
    name: build new docker image
    needs: check
    if: needs.check.outputs.needs-updating == 'true' || github.event.inputs.force_build == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/rfdrake/tftpd-hpa:latest
